### ISSUE TITLE
Info on external relay driver (Esparagus HiFi MediaLink)

### ISSUE THREAD

**Issue by HiFiJ** [sonocotta/esparagus-media-center#4]
Hello,

could you provide some insight on how to use the relay driver interface, esp. software-side, does it switch on automatically when playing, when doses it switch off, manual toggle etc?

Thanks for the very cool project, pretty satisfied so far,

Joost

**Comment by anabolyc** [comment]
Hey @HiFiJ

Since HiFi Esparagus is a line-level device, it is used with an external amplifier usually (at least I do). The relay driver should be used to only turn on the external amp via a relay when it is needed (old amps draw quite a lot of power in standby). 

You should be able to use `mute` setting in [DAC config](https://github.com/sle118/squeezelite-esp32/?tab=readme-ov-file#daci2s). Then it is connected to replay that is in parallel to power switch. 
![image](https://github.com/sonocotta/esparagus-media-center/assets/5459747/194a235a-80c8-4478-b9dc-aa5f27561d5c)

Mind you, I did not test it yet with HiFi-Esparagus, I have used it in different setup (raspberry pi based, wip)
